import { Election } from "@equal-vote/star-vote-shared/domain_model/Election";
import { ElectionRoll, ElectionRollState, NewElectionRoll } from "@equal-vote/star-vote-shared/domain_model/ElectionRoll";
import { IRequest } from "../../IRequest";
import ServiceLocator from "../../ServiceLocator";
import Logger from "../../Services/Logging/Logger";
import { InternalServerError, Unauthorized } from "@curveball/http-errors";
import { ILoggingContext } from "../../Services/Logging/ILogger";
import { hashString } from "../controllerUtils";
import { logSafeHash } from "../../Services/Logging/logSafeHash";
import { makeUniqueID, ID_LENGTHS, ID_PREFIXES } from "@equal-vote/star-vote-shared/utils/makeID";

const ElectionRollModel = ServiceLocator.electionRollDb();

// Finds the requester's roll entry, creating it if they're allowed one and don't have one yet.
// Used when a vote is cast. Creation is atomic per voter (see ElectionRollModel.findOrCreateRoll).
export async function getOrCreateElectionRoll(req: IRequest, election: Election, ctx: ILoggingContext, voter_id_override?: string, skipStateCheck?: boolean): Promise<ElectionRoll | null> {
    return resolveElectionRoll(req, election, ctx, true, voter_id_override, skipStateCheck);
}

// Read-only variant for requests that only show the election (GET /Election/:id and
// POST /Election/:id/ballot). It never writes: when an open-access voter has no roll entry
// yet it returns an unsaved provisional one, and the real row is created when they vote.
export async function getElectionRollForRequest(req: IRequest, election: Election, ctx: ILoggingContext): Promise<ElectionRoll | null> {
    return resolveElectionRoll(req, election, ctx, false);
}

async function resolveElectionRoll(req: IRequest, election: Election, ctx: ILoggingContext, persist: boolean, voter_id_override?: string, skipStateCheck?: boolean): Promise<ElectionRoll | null> {
    // Checks for existing election roll for user
    Logger.info(req, `resolveElectionRoll persist=${persist}`)
    const ip_hash = hashString(req.ip!)
    // Get data that is used for voter authentication
    // NOTE: I'm ensuring that undefined is coaleced into null, that makes it compliant with the type when calling getElectionRoll
    const require_ip_hash = (election.settings.voter_authentication.ip_address ? ip_hash : null) ?? null;
    const email = election.settings.voter_authentication.email ? (req.user?.email ?? null) : null
    
    // Get voter ID if required and available, otherwise set to null
    let voter_id = null
    if (election.settings.voter_authentication.voter_id && election.settings.voter_access == 'closed') {
        // cookies don't support special charaters
        // https://help.vtex.com/en/tutorial/why-dont-cookies-support-special-characters--6hs7MQzTri6Yg2kQoSICoQ
        voter_id = voter_id_override ?? atob(req.cookies?.voter_id); 
    } else if (election.settings.voter_authentication.voter_id && election.settings.voter_access == 'open') {
        voter_id = voter_id_override ?? req.user?.sub ?? null
    }

    // Get all election roll entries that match any of the voter authentication fields
    // This is an odd way of going about this, rather than getting a roll that matches all three we get all that match any of the fields and
    // check the output for a number of edge cases.
    let electionRollEntries = null
    if ((require_ip_hash || email || voter_id)) {
        electionRollEntries = await ElectionRollModel.getElectionRoll(String(election.election_id), voter_id, email, require_ip_hash, ctx);
    }

    if (electionRollEntries == null) {
        // No election roll found, create one if voter access is open and election state is open
        if (election.settings.voter_access !== 'open') return null
        if (!skipStateCheck && election.state !== 'open') return null

        const shouldPersist = persist && !!(require_ip_hash || email || voter_id);
        Logger.info(req, shouldPersist ? "Creating new roll" : "No roll yet; using an unsaved provisional entry");
        const new_voter_id = (election.settings.voter_authentication.voter_id || !shouldPersist) ?
            (voter_id ?? '') :
            await makeUniqueID(
                ID_PREFIXES.VOTER,
                ID_LENGTHS.VOTER,
                async (id: string) => await ElectionRollModel.getByVoterID(String(election.election_id), id, ctx) !== null,
            );
        const history = [{
            action_type: ElectionRollState.approved,
            actor: new_voter_id,
            timestamp: Date.now(),
        }]
        // create_date / update_date / head are generated by the model in the insert transaction.
        const roll: NewElectionRoll[] = [{
            election_id: String(election.election_id),
            email: req.user?.email ? req.user.email : undefined,
            voter_id: new_voter_id,
            ip_hash: ip_hash,
            submitted: false,
            state: ElectionRollState.approved,
            history: history,
        }]
        if (!shouldPersist) {
            // Not persisted; downstream code that needs a real update_date should not reach here.
            return { ...roll[0], update_date: Date.now().toString(), head: true, create_date: new Date().toISOString() }
        }
        // Atomic find-or-insert: a concurrent first request from the same voter may have created
        // the row in the meantime, in which case we get that row back and fall through to the
        // same checks as an existing roll. Returning the stored row matters because its
        // update_date is what OCC checks on the cast-vote path.
        electionRollEntries = await ElectionRollModel.findOrCreateRoll(
            roll[0],
            { voter_id, email, ip_hash: require_ip_hash },
            ctx,
            `User requesting Roll and is authorized`,
        );
    }


    if (electionRollEntries.length > 1) {
        // Multiple election rolls match some of the authentication fields, shouldn't occur but throw error if it does
        // Maybe could happen if someone submits valid voter ID seperate valid email
        Logger.error(req, `Multiple election roll entries found (${electionRollEntries.length} entries)`);
        throw new InternalServerError('Multiple election roll entries found');
    }
    if (election.settings.voter_authentication.ip_address && electionRollEntries[0].ip_hash) {
        if (electionRollEntries[0].ip_hash !== ip_hash) {
            Logger.error(req, `IP Address does not match saved voter roll, voter: ${logSafeHash(electionRollEntries[0].voter_id)}`);
            throw new Unauthorized('IP Address does not match saved voter roll');
        }
    }
    if (election.settings.voter_authentication.email && electionRollEntries[0].email !== email) {
        // Email doesn't match saved election roll, for example if email and voter ID are selected but email doesn't match the voter ID 
        Logger.error(req, `Email does not match saved election roll, voter: ${logSafeHash(electionRollEntries[0].voter_id)}`);
        throw new Unauthorized('Email does not match saved election roll');
    }
    if (election.settings.voter_authentication.voter_id && electionRollEntries[0].voter_id.trim() !== (voter_id ?? '').trim()) {
        // Voter ID does not match saved election roll, for example if email and voter ID are selected but email doesn't match the voter ID 
        Logger.error(req, `Voter ID does not match saved election roll, voter: ${logSafeHash(electionRollEntries[0].voter_id)}`);
        throw new Unauthorized('Voter ID does not match saved voter roll');
    }

    return electionRollEntries[0]

}

// NOTE: voter_id can be directly passed in for bulk ballot uploads, but usually it will be retrieved from the cookies
export function checkForMissingAuthenticationData(req: IRequest, election: Election, ctx: ILoggingContext, voter_id?: string): string | null {
    // Checks that user has provided all data needed for authentication
    Logger.info(req, `checkForMissingAuthenticationData`)
    if ((election.settings.voter_authentication.voter_id && election.settings.voter_access == 'closed') && !(voter_id ?? req.cookies?.voter_id)) {
        return 'Voter ID Required for closed elections'
    }
    // Arend's Note: I don't think 'User ID Required' is used anymore, might be a remnant of when we were thinking of custom authentication flows, but we don't have a clear story for that at the moment.
    // Arend's second note: This is still possible, this happens with "one vote per device" security settings and the cookies aren't set properly
    if ((election.settings.voter_authentication.voter_id && election.settings.voter_access == 'open') && !(req.user)) {
        return "Temp ID is required for open elections with 'one vote per device' authentication"
    }
    if (election.settings.voter_authentication.email && !(req.user?.email)) {
        return 'Email Validation Required'
    }
    return null
}

export function getVoterAuthorization(roll: ElectionRoll | null, missingAuthData: string | null) {
    Logger.info(undefined, `getVoterAuthorization`)
    if (missingAuthData !== null) {
        Logger.info(undefined, missingAuthData)
        return {
            authorized_voter: false,
            required: missingAuthData,
            has_voted: false,
        }
    }
    if (roll === null) {
        return {
            authorized_voter: false,
            has_voted: false,
        }
    }
    return {
        authorized_voter: true,
        has_voted: roll.submitted,
    }
} 
