// NOTE: I'm putting this in a separate file so that the documentation is easy to reference

/* Random Tiebreaker Details
 * 
 * Our random tiebreaker protocol is written to be deterministic to ensure that we get the same results regardless of
 *   how many times the tabulator is re-run
 *
 * ## Generating the seed
 *
 * The seed is generated by adding 2 components
 * 
 *  1. Raw Votes:
 *       This ensures the tiebreak priority is reset after every vote. Raw votes is not to be confused with Tally Votes. Raw votes refers
 *       to the number of ballots you would see when downloading the full data, however the results page shows tally votes. The Tally Votes filters
 *       out invalid votes from the Raw Votes so the count is often smaller.
 * 
 *  2. Race Offset:
 *       Each Race Id gets a different offset value. It's common for users to create multi-method polls with the same candidates on BetterVoting, and
 *       without the offset those polls would have the same tiebreaking result on each race. The offset helps ensure variation.
 *
 * ## Shuffling
 *
 * For shuffling we use the TinyRand library https://github.com/tim-one/tinyrand/tree/main
 *
 * TinyRand is small, and it's written to be language agnostic so that results can be easily reproduced in any programming language.
 */

import {get as getTinyRand} from './tinyrand';
import { candidate } from "@equal-vote/star-vote-shared/domain_model/ITabulators";

// NOTE: electionCreateDate is currently unused, but if we ever change the approach for shuffling the candidates then
//       we should use electionCreateDate to ensure that old elections still use the old approach
export default  (electionCreateDate: Date | string, candidates: candidate[], rawVoteCount: number, raceId: string) => {
    const hashStringToInt = (str: string) => {
        // this function just converts the string into a number we can feed into the seed;
        return [...str].reduce((h, c) => (Math.imul(31, h) + c.charCodeAt(0)) | 0, 0);
    }

    // >>> 0 coerces to unsigned 32-bit (wraps negatives to large positives) rather than Math.abs (which folds -x and +x onto the same value, halving the seed space)
    let seed = (rawVoteCount + hashStringToInt(raceId)) >>> 0;
    getTinyRand(0, seed).shuffle(candidates)
    candidates.forEach((c, i) => c.tieBreakOrder = i)
}