remote_theme: just-the-docs/just-the-docs
color_scheme: custom
logo: images/logo.png


# https://github.com/just-the-docs/just-the-docs/discussions/1583
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red